### ISSUE TITLE
CUDA 8 cuDNN 5 clone gets "Attribute Error: 'NoneType' object has no attribute 'rfind'"

### ISSUE THREAD

**Issue by thommiano** [alexjc/neural-doodle#104]
I cloned the [source image](https://github.com/alexjc/neural-doodle) via `git clone` on github rather than using `docker git clone` because I couldn't quite figure out if there was a way to do that. I made the following changes:

- CUDA8: https://github.com/thommiano/neural-doodle/blob/master/docker/install-cuda-drivers-ubuntu-14.04.sh
- CUDA8 and cuDNN5: https://github.com/thommiano/neural-doodle/blob/master/docker-gpu.df
- Duplicated docker-gpu.df and renamed it Dockerfile in order to create a docker image. Then removed docker-gpu.df and docker-cpu.df. Couldn't figure out how run the image otherwise since I cloned it from github. Any pointers on the right way to do this would be appreciated.

I then pushed it up to [my remote](https://github.com/thommiano/neural-doodle), built the docker image, and pushed that to dockerhub.

Now when I run `nvidia-docker run socraticdatum/neural-doodle` I get the following:

````
Neural Doodle for semantic style transfer.
  - Using device `gpu` for processing the images.
Traceback (most recent call last):
  File "doodle.py", line 657, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 234, in __init__
    self.style_img_original, self.style_map_original = self.load_images('style', args.style)
  File "doodle.py", line 288, in load_images
    basename, _ = os.path.splitext(filename)
  File "/usr/lib/python3.4/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/usr/lib/python3.4/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'
````
I think this is at least an improvement because it's now saying `Using device `gpu` for processing the images`, but I'm not quite sure how to fix the `rfind` problem. Any ideas on this?

**Comment by sakaizumi** [comment]
I need your help, i have the same problems with you, do you solve this problem?
If you solved it, please tell me how to solve it, thank you!

**Comment by thommiano** [comment]
No I didn't. Looking back, I'm not sure if I did what [LazyMammal suggested](https://github.com/alexjc/neural-doodle/issues/96). I would start there first.

**Comment by ProGamerGov** [comment]
Has anyone figured out a solution to this issue yet?

**Comment by maki-chan** [comment]
I know this answer is very late, but:

Using the Ubuntu 14.04 version of the GPU container specifically works flawlessly on my side which is missing in your Dockerfile @thommiano 
It is probably an incompatibility with Python 3.5+ which is used by Ubuntu versions after 14.04

You can take a look at the docker-gpu.df file in my fork of this project which does not clone the 16.04 Ubuntu version, but specifically clones from the CUDA 8 on Ubuntu 14.04 image. Furthermore, there were two changes I made to the `requirements.txt` file, using a Pillow version below 6.0 (as only versions up to 5.x work on Ubuntu 14.04 due to Python 3.4 being used) and using a specific Theano version to avoid further incompatibility issues.

This is the fork: https://github.com/maki-chan/neural-doodle
